# Site settings
title: Engenheiro de Dados
description: Um Portfólio e CV
# baseurl: ""
url: "http://pand-eX.github.io"

# User settings
username: Henrique M Castro
user_description: Depois eu falo um pouco sobre...
user_title: Engenheiro de Dados
email: henricao_7@yahoo.com.br
twitter_username: https://twitter.com/pandeX__
github_username:  https://github.com/pand-eX
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
