# Site settings
title: Data Engineer
description: Portfólio
# baseurl: ""
url: "http://pand-eX.github.io"

# User settings
username: Henrique M Castro
user_description: Tudo começou quando eu estava trabalhando com Quant Trading no mercado de ações e os dados que eu precisava vieram todos desconfigurados e com caracteres errados e sem integridade. Portanto, eu decido fazer um curso para levar esses dados diretamente à minha fonte de análise financeira. Quando comecei a estudar descobri um mundo totalmente incrível com grandes possibilidades e me apaixonei por esses processos para extrair, processar e carregar para o seu destino corretamente. E por que decidi abandonar a análise Quant Tranding? Ao invés de me preocupar com variáveis e ponto e vírgulas eu me preocupo com modelos e pipelines de dados, isso me permite pensar sobre os problemas de forma diferente ao invés de ficar preso no código, eu consigo pensar de forma mais realista sobre abordagens e métodos diferentes e tento entender qual é o mais adequado para a solução que estou construindo.
user_title: Data Engineer
email: "henricao_7@yahoo.com.br"
twitter_username: "https://twitter.com/@pandeX__"
github_username: "https://github.com/pand-eX"
linkedin_username: "https://www.linkedin.com/in/henrique-castro-484269203/"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
