# Site settings
title: Engenheiro de Dados
description: Um Portfólio e CV
# baseurl: ""
url: "http://pand-eX.github.io"

# User settings
username: Henrique M Castro
user_description: Olá sou considerado um geek gosto de estar ligado nas tendências da tecnologia e como ela pode impactar não só a minha vida mas de uma companhia. Busco usar o processo de ETL(Extract, Transform and Load) para preparar os dados para uso analítico ou operacional lidando com conjuntos de dados estruturados e não estruturados aplicando uma variedade de ferramentas tecnológica.
user_title: Engenheiro de Dados
email: henricao_7@yahoo.com.br
twitter_username: "https://twitter.com/pandeX__"
github_username: https://github.com/pand-eX"
gplus_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
