# Site settings
title: Data Engineer
description: Portfólio
# baseurl: ""
url: "http://pand-eX.github.io"

# User settings
username: Henrique M Castro
user_description: It all started when i was working with quant trade and the data i need was coming all misconfigured and errored. So you decide to take a course to get this data right to my source of financial analysis. When I started studying I found a totally amazing world with high possibilities and fell in love with building these processes to extract and take to their destination correctly. And why did I decide to abandon the quant analysis? Instead of worrying about variables and semicolons I care about models and data pipelines, this allows me to think about problems differently rather than getting stuck in the code, I can think more realistically about different approaches and methods and try to understand which is best suited for the solution I'm building.
user_title: Data Engineer
email: "henricao_7@yahoo.com.br"
twitter_username: "https://twitter.com/@pandeX__"
github_username: "https://github.com/pand-eX"
linkedin_username: "https://www.linkedin.com/in/henrique-castro-484269203/"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
