# Site settings
title: Engenheiro de Dados
description: Um Portfólio e CV
# baseurl: ""
url: "http://pand-eX.github.io"

# User settings
username: Henrique M Castro
user_description: Sou considerado um geek gosto de estar ligado nas tendências da tecnologia e como ela pode impactar não só a minha vida mas também de uma companhia. Busco usar o processo de ETL(Extract, Transform and Load) para preparar e carregar os dados para uso analítico ou operacional lidando com conjuntos de dados estruturados e não estruturados aplicando uma variedade de ferramentas tecnológica.  Eu gosto de utilizar meu conhecimento para criar sistemas e resolver problemas, seja ele de processamento de dados em Batch ou Streaming(em tempo real) e manipular quantidades imensas de dados. Eu tenho a responsabilidade de transformar uma aplicação analítica em produtos ou serviços e que pode usar arquitetura de Microserviços para isso! Meu proposito é resolver problemas e fornecer soluções e plataformas de Big Data modulares e escaláveis para que os Cientistas de dados possam fazer seu trabalho de análise.   "Se você não sabe para onde quer ir, então, qualquer caminho serve."" 
user_title: Engenheiro de Dados
email: "henricao_7@yahoo.com.br"
twitter_username: "https://twitter.com/@pandeX__"
github_username: "https://github.com/pand-eX"
linkedin_username: "https://www.linkedin.com/in/henrique-castro-484269203/"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
