# Site settings
title: Data Engineer
description: Portfólio
# baseurl: ""
url: "http://pand-eX.github.io"

# User settings
username: Henrique M Castro
user_description: It all started when I was working with quantum trading in the stock market and the data I needed came all misconfigured and wrong. Therefore, I decide to take a course to get this data directly to my source of financial analysis. When I started studying I discovered a totally amazing world with great possibilities and fell in love with these processes to extract and take to their destination properly. And why did I decide to abandon quantum analysis? Instead of worrying about variables and semicolons I worry about data models and pipelines. this allows me to think about problems differently rather than getting stuck in the code, I can think more realistically about different approaches and methods and try to understand which one is best suited for the solution I'm building.
user_title: Data Engineer
email: "henricao_7@yahoo.com.br"
twitter_username: "https://twitter.com/@pandeX__"
github_username: "https://github.com/pand-eX"
linkedin_username: "https://www.linkedin.com/in/henrique-castro-484269203/"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
