# Site settings
title: Data Engineer
description: Portfólio
# baseurl: ""
url: "http://pand-eX.github.io"

# User settings
username: Henrique M Castro
user_description: I am considered a geek to be connected to technology trends and how it can impact not only my life but also a company. I seek to use the Extract(Transform and Load) ETL (ETL) process to prepare and load data for analytical or operational use by dealing with structured and unstructured data sets by applying a variety of technological tools. I like to use my knowledge to create systems and solve problems, be it batch or streaming data processing and manipulating huge amounts of data. I have a responsibility to turn an analytical application into products or services and i can use Microservices architecture for this! My purpose is to solve problems and provide modular and scalable big data solutions and platforms so that data scientists can do their analysis work. If you don't know where you want to go, then any path will do.
user_title: Data Engineer
email: "henricao_7@yahoo.com.br"
twitter_username: "https://twitter.com/@pandeX__"
github_username: "https://github.com/pand-eX"
linkedin_username: "https://www.linkedin.com/in/henrique-castro-484269203/"

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
